steps:
- name: '${_BUILD_NAMESPACE}/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-app:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-app:latest'
    - './docker/p4-gpi-app'
- name: '${_BUILD_NAMESPACE}/cloud-builders/docker'
  waitFor: ['-']
  args:
    - 'build'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-openresty:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-openresty:latest'
    - './docker/p4-gpi-openresty'

images:
  - ${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-app:${_BUILD_TAG}
  - ${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-app:latest
  - ${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-openresty:${_BUILD_TAG}
  - ${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-gpi-openresty:latest
