substitutions:
  _BRANCH_NAME: develop
  _BUILD_NAMESPACE: gcr.io
  _BUILD_NUM: local
  _PROJECT_ID: planet-4-151612
steps:
- id: 'p4-gpi-app-dev'
  name: '${_BUILD_NAMESPACE}/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-app-dev:${_BRANCH_NAME}'
    - '--tag=${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-app-dev:build-${_BUILD_NUM}'
    - 'p4-gpi-app-dev'
- id: 'p4-gpi-openresty-dev'
  name: '${_BUILD_NAMESPACE}/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-openresty-dev:${_BRANCH_NAME}'
    - '--tag=${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-openresty-dev:build-${_BUILD_NUM}'
    - 'p4-gpi-openresty-dev'
  waitFor: ['-']

images:
  - ${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-app-dev:${_BRANCH_NAME}
  - ${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-app-dev:build-${_BUILD_NUM}
  - ${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-openresty-dev:${_BRANCH_NAME}
  - ${_BUILD_NAMESPACE}/${_PROJECT_ID}/p4-gpi-openresty-dev:build-${_BUILD_NUM}
